### ISSUE TITLE
Intermittent serial msp problem

### ISSUE THREAD

**Issue by haslinghuis** [betaflight/betaflight-configurator#2498]
![Screenshot from 2021-05-30 00-33-00](https://user-images.githubusercontent.com/8344830/120086347-b3fe6b00-c0de-11eb-8019-15216c0a1314.png)

This ugly hack seems to resolve the issue having `apiVersion` undefined.
The error is very intermittent and therefor hard to catch, at the looks of it, it seems it has to do with multiple connections or msp crc errors, but it's just a thought.

```
PortHandler - Removed: [{"path":"/dev/ttyACM0","displayName":"Betaflight STM32F411"}]
DevTools failed to load SourceMap: Could not load content for chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/node_modules/jquery-textcomplete/dist/dist/jquery.textcomplete.min.map: System error: net::ERR_FILE_NOT_FOUND
port_handler.js:159 PortHandler - Found: [{"path":"/dev/ttyACM1","displayName":"Betaflight STM32F411"}]
serial_backend.js:69 serial: connecting to: /dev/ttyACM1
serial.js:110 serial: connection opened with ID: 4 , Baud: 115200
serial_backend.js:249 Requesting configuration data
main.html#:1 Error in event handler: TypeError: Invalid Version: null.null.0
    at new l (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/node_modules/semver-min/umd/index.js:1:4884)
    at I (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/node_modules/semver-min/umd/index.js:1:8498)
    at Object.L [as gte] (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/node_modules/semver-min/umd/index.js:1:8702)
    at MspHelper.process_data (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/msp/MSPHelper.js:772:28)
    at chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/msp.js:229:13
    at Array.forEach (<anonymous>)
    at Object.notify (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/msp.js:228:24)
    at Object._dispatch_message (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/msp.js:219:14)
    at Object.read (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/msp.js:186:22)
    at read_serial (chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/serial_backend.js:590:13)
msp.js:347 MSP data request timed-out: 4 direction: 1 tab: landing
```

**Comment by haslinghuis** [comment]
The problem looks to be multiple connections and not letting the code continue switching tabs too soon. Already introduced a check if the connections is still active.
